#include "countries.h"
#include <string.h>

static const struct CountryMapping country_mappings[] = {
    {"AF", "Afghanistan"},
    {"AL", "Albania"},
    {"DZ", "Algeria"},
    {"AD", "Andorra"},
    {"AO", "Angola"},
    {"AR", "Argentina"},
    {"AM", "Armenia"},
    {"AU", "Australia"},
    {"AT", "Austria"},
    {"AZ", "Azerbaijan"},
    {"BS", "Bahamas"},
    {"BH", "Bahrain"},
    {"BD", "Bangladesh"},
    {"BY", "Belarus"},
    {"BE", "Belgium"},
    {"BO", "Bolivia"},
    {"BA", "Bosnia and Herzegovina"},
    {"BR", "Brazil"},
    {"BG", "Bulgaria"},
    {"KH", "Cambodia"},
    {"CM", "Cameroon"},
    {"CA", "Canada"},
    {"CL", "Chile"},
    {"CN", "China"},
    {"CO", "Colombia"},
    {"CR", "Costa Rica"},
    {"HR", "Croatia"},
    {"CU", "Cuba"},
    {"CY", "Cyprus"},
    {"CZ", "Czech Republic"},
    {"DK", "Denmark"},
    {"DO", "Dominican Republic"},
    {"EC", "Ecuador"},
    {"EG", "Egypt"},
    {"SV", "El Salvador"},
    {"EE", "Estonia"},
    {"ET", "Ethiopia"},
    {"FI", "Finland"},
    {"FR", "France"},
    {"GE", "Georgia"},
    {"DE", "Germany"},
    {"GH", "Ghana"},
    {"GI", "Gibraltar"},
    {"GR", "Greece"},
    {"GT", "Guatemala"},
    {"HT", "Haiti"},
    {"HN", "Honduras"},
    {"HK", "Hong Kong"},
    {"HU", "Hungary"},
    {"IS", "Iceland"},
    {"IN", "India"},
    {"ID", "Indonesia"},
    {"IR", "Iran"},
    {"IQ", "Iraq"},
    {"IE", "Ireland"},
    {"IL", "Israel"},
    {"IT", "Italy"},
    {"JM", "Jamaica"},
    {"JP", "Japan"},
    {"JO", "Jordan"},
    {"KZ", "Kazakhstan"},
    {"KE", "Kenya"},
    {"KR", "South Korea"},
    {"KW", "Kuwait"},
    {"LV", "Latvia"},
    {"LB", "Lebanon"},
    {"LY", "Libya"},
    {"LI", "Liechtenstein"},
    {"LT", "Lithuania"},
    {"LU", "Luxembourg"},
    {"MK", "North Macedonia"},
    {"MY", "Malaysia"},
    {"MT", "Malta"},
    {"MX", "Mexico"},
    {"MD", "Moldova"},
    {"MC", "Monaco"},
    {"MN", "Mongolia"},
    {"ME", "Montenegro"},
    {"MA", "Morocco"},
    {"NP", "Nepal"},
    {"NL", "Netherlands"},
    {"NZ", "New Zealand"},
    {"NI", "Nicaragua"},
    {"NG", "Nigeria"},
    {"NO", "Norway"},
    {"OM", "Oman"},
    {"PK", "Pakistan"},
    {"PA", "Panama"},
    {"PY", "Paraguay"},
    {"PE", "Peru"},
    {"PH", "Philippines"},
    {"PL", "Poland"},
    {"PT", "Portugal"},
    {"PR", "Puerto Rico"},
    {"QA", "Qatar"},
    {"RO", "Romania"},
    {"RU", "Russia"},
    {"SA", "Saudi Arabia"},
    {"RS", "Serbia"},
    {"SG", "Singapore"},
    {"SK", "Slovakia"},
    {"SI", "Slovenia"},
    {"ZA", "South Africa"},
    {"ES", "Spain"},
    {"LK", "Sri Lanka"},
    {"SE", "Sweden"},
    {"CH", "Switzerland"},
    {"SY", "Syria"},
    {"TW", "Taiwan"},
    {"TJ", "Tajikistan"},
    {"TH", "Thailand"},
    {"TN", "Tunisia"},
    {"TR", "Turkey"},
    {"TM", "Turkmenistan"},
    {"UA", "Ukraine"},
    {"AE", "United Arab Emirates"},
    {"GB", "United Kingdom"},
    {"US", "United States"},
    {"UY", "Uruguay"},
    {"UZ", "Uzbekistan"},
    {"VA", "Vatican City"},
    {"VE", "Venezuela"},
    {"VN", "Vietnam"},
    {"YE", "Yemen"},
    {NULL, NULL}  // terminator
};

const char* GetCountryNameFromCode(const char *code) {
    if (!code) return "Unknown";

    for (int i = 0; country_mappings[i].code != NULL; i++) {
        if (stricmp(country_mappings[i].code, code) == 0) {
            return country_mappings[i].name;
        }
    }

    return code;  // Return code if no match found
}
